// Package vectors holds the FEE (FilOne File Encryption Envelope)
// cross-implementation test vectors: fixed fixture blobs that must decrypt
// identically under this Go implementation (fee/cose, fee/aesstream,
// fee/ecdhkw, fee/aeskw) and under the TypeScript reference implementation,
// foc-encryption (github.com/Kubuxu/foc-encryption-demo, packages/
// foc-encryption), pinned in pull-foc-encryption.sh.
//
// The reference is the source of truth for the wire format. Its shape, verified
// against the pinned commit, is:
//
//	blob        = envelope || ciphertext          (detached payload)
//	envelope    = 16([protected, unprotected, null])                for no recipients
//	            | 96([protected, unprotected, null, recipients])    with recipients
//	protected   = {1: alg, 16: "application/vnd.foc-envelope+cose"}
//	unprotected = {5: baseNonce, -65790: chunkSize, -65791: chunkCount}
//	alg         = -65793  (chunked AES-256-GCM-STREAM)
//	body AAD    = [ "Encrypt0", protected, "" ]   -- always the Encrypt0
//	              context, even for a tag-96 multi-recipient envelope
//	chunk nonce = baseNonce[7] || chunkIndex[4 BE] || lastFlag[1]
//
// A recipient entry is [ {1: alg}, {4: kid, ...}, wrappedKey ]. The reference
// carries wrappedKey opaquely and never unwraps it — decryption takes the CEK
// directly — so cross-implementation coverage of the recipient layer proves the
// reference parses our recipient descriptors and decrypts the body from the
// shared CEK; the actual CEK unwrap (ECDH-ES+A256KW over X25519, and A256KW) is
// asserted on the Go side in vectors_test.go.
//
// Fixtures live under testdata/<name>/ as blob.bin, plaintext.bin and
// meta.json. TestVectors reads and verifies every fixture. The Go-produced
// fixtures are (re)generated by TestGenerate (guarded by FEE_VECTORS_REGEN=1);
// the TS-produced ones by pull-foc-encryption.sh, which also confirms the real
// foc-encryption decrypts the Go-produced fixtures. See README.md.
package vectors
